Fix infinite election
yandex/pgconsul pull request #27
Opened 2024-07-16 13:30 UTC by munakoiso

When old master is gone, election can look like this:
Hosts in group A are waiting for the get_alive_hosts call at moment X in the _can_do_failover function. Each pgconsul inside of get_alive_hosts waits for each host's health to timeout = election_timeout / 2.
The hosts in group B start the election at moment X and wait for all active hosts to vote. The timeout is set to election_timeout / 2.

Hosts in group A at time X+election_ timeout/2 will mark the old master as dead and start an election (thus, A will become B). 
Hosts in group B, at moment X + election_timeout/2, will mark the election as failed due to hosts from group A. Then, a new iteration will start (thus, B becomes A).

So, we need to decrease timeout in get_alive_hosts. 
Also, we need to make that timeout works for all hosts in total, not for each of it.

2024-07-16 13:31 UTC, EinKrebs approved these changes

2024-07-16 14:06 UTC, vicpopov requested changes

2024-07-16 14:06 UTC, vicpopov commented on src/zk.py
> +            timeout = max(timeout, all_hosts_timeout // len(ha_hosts))
How about adding at least a warning, if `all_hosts_timeout // len(ha_hosts)` is less then `timeout`?

Also, you can exceed overall timeout of `election_timeout / 2` if `timeout` is picked here, even if `all_hosts_timeout = election_timeout / 2`.

2024-07-18 07:47 UTC, vicpopov requested changes

2024-07-18 07:47 UTC, vicpopov commented on src/zk.py
> +                logging.warning("The total timeout for checking the aliveness of all hosts (%s s) "
Here we do not obey explicitly given `all_hosts_timeout`, we should also log that actually `minimal_total_timeout` will be used.
Warning only would be sufficient if we would use given `all_hosts_timeout`.

2024-07-18 08:54 UTC, vicpopov approved these changes

2024-07-19 08:47 UTC, merged